#preload = ~/.config/backgrounds/shaded.png
#wallpaper = DP-2, ~/.config/backgrounds/shaded.png
wallpaper {
  monitor =
  path = ~/.config/backgrounds/shaded.png
  fit_mode = cover
  #timeout = 10 -> 10s para cambiar entre wallpapers?
}
